version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my_symfony_app
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - '3306:3306'
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql
  webserver:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  db-data: